image: wordpress

before_script:
  - apt-get update -qq && apt-get install -y -qq redis-server wget git subversion mysql-server
  - wget https://getcomposer.org/download/1.0.2/composer.phar
  - chmod +x composer.phar
  - ./composer.phar self-update
  - ./composer.phar install --no-interaction --prefer-source
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest

test:
  script:
    php vendor/bin/phpunit
